import Head from "next/head";
import React from "react";

export default function register() {
  return (
    <>
      <Head>
        <title>Yeni Üye | Türkiye Vestelleniyor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
