import Head from "next/head";
import React from "react";
import ProductDetail from "../../../../components/ProductDetail/ProductDetail";

export default function productDetail({ productDetail }) {
  console.log("prodctDetail", productDetail);
  return (
    <>
      <Head>
        <title>
          {productDetail.Result.PageTitle
            ? productDetail.Result.PageTitle
            : "Vestel'le Olur Neden Olmasın | Vestel"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetail data={productDetail}/>
    </>
  );
}
export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://store.vrunibex.com/mobile2/mbProduct/ProductDetail?productId=${context.params.id}`
  );
  const productDetail = await res.json();
  return {
    props: {
      productDetail,
    },
  };
};
