import Head from "next/head";

export default function Home({category}) {
  console.log("category", category);
  return (
    <>
      <Head>
        <title>Vestel'le Olur Neden Olmasın | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Home Page</h1>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://store.vrunibex.com/mobile2/mbProduct/CategoryList"
  );
  const category = await res.json();
  return {
    props: {
      category,
    },
  };
};
