import Head from "next/head";
import React from "react";

export default function search() {
  return (
    <>
      <Head>
        <title>Arama Sayfası | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-xl-6 mx-auto my-3">
            <div className="input-group mb-3">
              <input
                type="text"
                className="form-control search-input"
                placeholder="Ürün, kategori, servis, mağaza ara"
              />
              <button className="btn search-button" type="button">
                Ara
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
